### ISSUE TITLE
Add Certificate Management

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/openevse_esp32_firmware#29]
- [ ] Disable root certificate validation per client
- [x] Update root certificates
- [ ] HTTPS server certificate/private key (GUI)
- [ ] MQTT client certificate/private key

**Comment by chris1howell** [comment]
Does this issue include client certificates? 

Client certificates are required for MQTT for use on Amazon AWS, Google Cloud, Microsoft Azure, etc.

Client Certificates are also required for OCPP 1.6J an 2.0 Security Profile 3 TLS with Client side certificate. 
https://www.openchargealliance.org/uploads/files/OCPP_1.6_Security_Whitepaper_-_2018.zip
