### ISSUE TITLE
Web server HTTPS

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/openevse_esp32_firmware#30]
Enable HTTPS support for the webserver, including changing the certificate and private key.

**Comment by ausil** [comment]
I use letsencrypt for certs on my emonpi, which is great. however, I am not sure that I want to expose my openevse to the internet for authentication to succeed. Perhaps there could be some tie-in to the emonpi to enable certificates to be authenticated and signed. using something like sniproxy could work well.

**Comment by jeremypoulter** [comment]
@ausil Interesting, for local in-home access? or are you accessing the emonpi remotely?

**Comment by ausil** [comment]
@jeremypoulter I am accessing it remotely, I have a few services I run at home behind sniproxy. I like to be able to monitor energy usage when I am traveling, I have tweaked the tls config on apache to make things as secure as I can
