### ISSUE TITLE
mDNS not working in development builds

### ISSUE THREAD

**Issue by ausil** [OpenEVSE/openevse_esp32_firmware#314]
running a recent development build mDNS discovery did not work. I have 2 OpenEVSE chargers and only the one running the 4.1.1 firmware showed up

`$ avahi-browse -t -r _openevse._tcp
+   eth0 IPv4 openevse1                                     _openevse._tcp       local
=   eth0 IPv4 openevse1                                     _openevse._tcp       local
   hostname = [openevse1.local]
   address = [172.17.46.11]
   port = [80]
   txt = ["type=openevse_huzzah32" "version=4.1.1" "id=246f28a6d220"]
`
Downgrading the second one to the 4.1.1 release firmware had it show up again

`$ avahi-browse -t -r _openevse._tcp
+   eth0 IPv4 openevse2                                     _openevse._tcp       local
+   eth0 IPv4 openevse1                                     _openevse._tcp       local
=   eth0 IPv4 openevse2                                     _openevse._tcp       local
   hostname = [openevse2.local]
   address = [172.17.46.210]
   port = [80]
   txt = ["type=openevse_wifi_v1" "version=4.1.1" "id=e0e2e6040760"]
=   eth0 IPv4 openevse1                                     _openevse._tcp       local
   hostname = [openevse1.local]
   address = [172.17.46.11]
   port = [80]
   txt = ["type=openevse_huzzah32" "version=4.1.1" "id=246f28a6d220"]
`

**Comment by ausil** [comment]
It may be that it is crashing on the "openevse_wifi_v1" hardware.  a current run of avahi-browse gives me 
` avahi-browse -t -r _openevse._tcp
+   eth0 IPv4 openevse2                                     _openevse._tcp       local
+   eth0 IPv4 openevse1                                     _openevse._tcp       local
=   eth0 IPv4 openevse1                                     _openevse._tcp       local
   hostname = [openevse1.local]
   address = [172.17.46.11]
   port = [80]
   txt = ["type=openevse_huzzah32" "version=4.1.1" "id=246f28a6d220"]
Failed to resolve service 'openevse2' of type '_openevse._tcp' in domain 'local': Timeout reached
`

**Comment by glynhudson** [comment]
Is this still an issue?

**Comment by glynhudson** [comment]
Is this still an issue?

**Comment by ausil** [comment]
It is not an issue with 4.1.9
