### ISSUE TITLE
Max Current limited to 12A

### ISSUE THREAD

**Issue by doppiaemme** [OpenEVSE/openevse_esp32_firmware#343]
Hi, 
I don't know when this issue started but I didn't have this issue before.
Same car (Renault Zoe, same wallbox), the only thing I did was to upgrade to 4.1.2 some weeks ago.
What happens is the max current is limited to 12A with Service level 1 and 9A with Service level 2.
Before I was able to select much more than 12 A and I kept Service level to Auto.
Now I can't get more than 12A and if I manually change SL to 1, it switches back to Auto.

any clue?

<img width="948" alt="image" src="https://user-images.githubusercontent.com/3978350/162753498-76badaa3-5bda-40dc-9de6-08e2176ad55d.png">

**Comment by glynhudson** [comment]
Did you download the pre-compiled EmonEVSE release? 

I would recommend updating to 8.2.0.T2 which is the latest version, download `emonevse.hex` from here: https://github.com/OpenEVSE/open_evse/releases/tag/8.2.0

**Comment by doppiaemme** [comment]
> Did you download the pre-compiled EmonEVSE release?
> 
> I would recommend updating to 8.2.0.T2 which is the latest version, download `emonevse.hex` from here: https://github.com/OpenEVSE/open_evse/releases/tag/8.2.0

I just did and that seems to have done the trick. now under Level 2 I see all the currents I was missing before! 
Thank you.

one question, if I am on service Level 2 and I change it to Auto, it goes back to 2
Same thing if I am on S. Level 1 and change it to Auto, it goes back to 1 by itself.
Is this correct? what is Auto for? 
Before I recall having it set to auto and never really bothered?

**Comment by doppiaemme** [comment]
I guess this is the reason:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/3978350/162774633-d759a511-5a3b-4dd8-a900-b0a4b208e273.png">

but why does it need to be locked?

**Comment by jeremypoulter** [comment]
The EU firmware disables auto level setting, but there is no way to detect this (short of trying to set it) so we don't remove from the UI

**Comment by doppiaemme** [comment]
> The EU firmware disables auto level setting, but there is no way to detect this (short of trying to set it) so we don't remove from the UI

Ok, I get that, but then why does the fw allows to manually select L1 in EU? my understanding is that L1 is for 120V and up to 15A for typical wall sockets in the US. If he stops selecting Auto, it should also stops from selecting L1?

**Comment by doppiaemme** [comment]
I have also just noticed that the Max Current limit is not honoured when charging in Normal mode.
To reproduce it I have to unplug an plug back in, it goes straight to 24A even if sets to let's say 14A. To make it really use 14A I have to select first 15A then 14A.
I tried to restart both the wifi module and the EVSE but it doesn't change
