### ISSUE TITLE
LCD not refreshed correctly with fw update

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/openevse_esp32_firmware#597]
following this from @glynhudson  : https://github.com/KipK/openevse-gui-v2/issues/46

**Comment by KipK** [comment]
Seems there's something wrong in the lcd service on wifi side. 
When  lcd.display is called , the content get overwritten sometime by the main loop without taking care of the display time value
Also when LCD_CLEAR_LINE | LCD_DISPLAY_NOW flags are set for booth lcd lines consecutively, first line doesn't get updated and stays frozen by main loop content ( i.e. "Zzz Sleeping zzZ" )

I've also got this issue while improving a bit RFID code

**Comment by KipK** [comment]
We should also add a scroll from left to right when the text overflows the 16 char

**Comment by jeremypoulter** [comment]
@KipK Can you give a more concrete example?

**Comment by KipK** [comment]
Got this while trying to fix https://github.com/KipK/openevse-gui-v2/issues/46 
Give a look to it, you will probably get the same issue I got.
