### ISSUE TITLE
More accurate build names

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/openevse_esp32_firmware#662]
Many users are uploading the wrong build for their hardware. File names for all hardware begin with openevse which is misleading. The following names are suggested to match the manufacture of hardware.

openevse_esp-wrover-kit.bin
espressif_esp-wrover-kit.bin

openevse_esp-wrover-kit_letest.bin
espressif_esp-wrover-kit_latest.bin

openevse_esp32-heltec-wifi-lora-v2.bin
heltec_esp32-wifi-lora-v2.bin

openevse_esp32-gateway-e_gui-v2.bin
olimex_esp32-gateway-e_gui-v2.bin

openevse_esp32-gateway-f_gui-v2.bin
olimex_esp32-gateway-f_gui-v2.bin

openevse_esp32-gateway-old_gui-v2.bin
olimex_esp32-gateway-old_gui-v2.bin

openevse_esp32-poe-iso.bin
olimex_esp32-poe-iso.bin

openevse_featheresp32.bin
adafruit_featheresp32.bin

openevse_nodemcu-32s.bin
nodemcu_ESP32s.bin

openevse_esp32-gateway-f_gui-v2.bin
olimex_esp32-gateway-f_gui-v2.bin

openevse_huzzah32.bin_gui-v2.bin
adafruit_huzzah32.bin_gui-v2.bin

**Comment by KipK** [comment]
It has changed now for dev builds . UI 1 has been removed. Next release
will use common names.

Le jeu. 25 mai 2023, 19:29, Chris Howell ***@***.***> a
écrit :

**Comment by KipK** [comment]
Oups I've misread, thought you were talking about the gui_v1 v2

**Comment by jeremypoulter** [comment]
Yeah agreed, now we have our own OpenEVSE board these names can be misleading, will update

**Comment by chris1howell** [comment]
It may also be a good idea to prefix the openevse version so it is the first on the list. It should be by far the most used version.

**Comment by glynhudson** [comment]
Totally agree, good idea :+1: 

Hopefully in the future it won't be so much of an issue since GUI V2 enables updating direct from github which should choose the correct release.
