### ISSUE TITLE
"Quit Wizard" button does not accomplish anything

### ISSUE THREAD

**Issue by fhteagle** [OpenEVSE/openevse_esp32_firmware#690]
Just loaded the  b8d1add  dev release on one of my units. After the firmware update completed, the unit restarted and the web UI went to the config wizard. Some of the config carried forward correctly, but the time went from NTP setting on old firmware to manual on new firmware. No big deal, fixed that, and hit next until the last screen where the button changed to "Quit Wizard". Clicked that, and the UI just went back around to the first card of the wizard, not to the main UI. Sat and waited maybe 30 seconds to see if it would reload itself or something, but no, just stayed on that card. Cleared the extra bits off the URL and manually went to the main UI no problem.

So the "Quit Wizard" button needs to go to the main URL for the unit, not back to the first config card.

**Comment by KipK** [comment]
Have you also updated and build the gui first?

It displays the Wizard only if the wizard_passed flag is not set.

**Comment by fhteagle** [comment]
Downloaded the precompiled .bin from here, not from a local compile.

**Comment by ruimarinho** [comment]
Similar thing here. In my case it required going through the wizard twice.

**Comment by DrFrankReade** [comment]
Same here, cloned and built from source  on August 20, 2023. 
![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/10439664/87ef2990-1fc8-41db-90b8-d032e12a2b8e)

**Comment by cscott** [comment]
Same here, twice -- ie, on both my chargers, I got sent back to the beginning by quit wizard the first time and had to run the wizard twice.  Maybe a race condition?  (Ie, the first page of the wizard is loaded before wizard_passed has been set?)
