### ISSUE TITLE
Shaper above max allowed power

### ISSUE THREAD

**Issue by gonzalezcalleja** [OpenEVSE/openevse_esp32_firmware#696]
Hi,

I'm using shaper with last dev build (master_517522f7) with this configuration:

<img width="761" alt="image" src="https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/3635557/df8e8bc8-b506-4767-a14d-acf02edc3e8b">

Live powered from shelly, updated every 3 seconds.

But the power used is above 5700:

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/3635557/b9aa504f-b317-47fa-ae9f-cb38cebd40ce)

In some cases it has exceeded 7500 and has caused a supply cut.

**Comment by KipK** [comment]
Can you post the published values from your Shelly?
What is your max current setting btw? It should not be above your 5700w
limit then, 23A.

**Comment by gonzalezcalleja** [comment]
> Can you post the published values from your Shelly? What is your max current setting btw? It should not be above your 5700w limit then, 23A. Le mar. 18 juil. 2023, 11:22, Javier González Calleja < ***@***.***> a écrit :
> […](#)

Hi @KipK, thanks for your answer.

About the values from the shelly, I think they are correct because I was using shaped with last version without problem until this update to dev version.

My max current settings is 32A, but with shaper I think that the first limit should limit by the "max power allow".

**Comment by gonzalezcalleja** [comment]
From mosquitto_sub, voltage:

<img width="504" alt="Screenshot 2023-07-19 at 05 32 03" src="https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/3635557/2eabf6a4-c88a-417f-b5db-0b501fb39a01">

Power:
<img width="504" alt="Screenshot 2023-07-19 at 05 33 36" src="https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/3635557/cad29d59-83a4-4c72-9067-e2ac12cf8006">

Log from openevse:

<img width="1099" alt="Screenshot 2023-07-19 at 05 34 10" src="https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/3635557/db8790c3-efff-48cf-acb1-bd1ce6c5374c">

**Comment by graememk** [comment]
Running the latest dev build, I'm coming across this too.

I'm using it to limit to the output of the batteries, but it didn't throttle the charge last night at all

Rolling back to the dev pre-release (may 15) it works as expected.

**Comment by MilorES** [comment]
OpenEVSE: 8.2.0.EU
OpenEVSE Wifi: v5.0.2

Same problem here:
![sharpererroneo](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/7502697/8cce030d-6055-4a98-9c3e-3a11e241b111)

How can you say that you have free 11.65A, 2800 - 1679 = 1130 / 230 = 4.9A

What version is recommended?
What is the decimal limit on voltage and power?
How long do you have to wait between data? Is 1s good? 5s? 10s?

I had to limit it to 6A, which is the minimum so as not to run out of electricity.

**Comment by graememk** [comment]
@jeremypoulter could this be merged with this one and closed? https://github.com/OpenEVSE/openevse_esp32_firmware/issues/762

@MilorES this is fixed in the nightly builds agaik and should be in the next release

**Comment by jeremypoulter** [comment]
Yeah, think that is the same issue

**Comment by MilorES** [comment]
@graememk So is it recommended to wear a  nightly build? Or better to wait for the new version?
How can you know when it will be released?

The current one is a couple of months old.
