### ISSUE TITLE
Session kWh just keeps goin up between different sessions?

### ISSUE THREAD

**Issue by pir8radio** [OpenEVSE/openevse_esp32_firmware#710]
The session KWH should show only what is/was consumed during current session or plug-in.  If I unplug and then plug back in, session should zero out and start a new SESSION...   right now session just keeps incrementing regardless of how many different cars charge You can see in the first screenshot today I have charged one vehicle and that vehicle used 7kwh yet session shows 18kwh from all previous charges days ago.  ![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/16748696/22c96d2a-eb68-4a15-9d0c-0efd56109c54) 

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/16748696/7ad0dae7-8952-4096-a828-66d732efcf46)

**Comment by fhteagle** [comment]
Just tested against master branch dev from about a week ago, session counter definitely reset to 0 at J1772 physical removal event. Does not seem to reset session on a power cycle though. Not sure what the intended behavior of that is supposed to be.

**Comment by KipK** [comment]
It is made to survive reboot yes. 

But I wonder where @pir8radio  problem comes from.
What is you Pause mode in settings/Evse? Is it set to disabled?

**Comment by pir8radio** [comment]
I will close this issue.. it seems this particular charger had really old EVSE firmware.   I made a mistake,  Updating the EVSE firmware seems to have fixed my issue..   Sorry to waste your time.
