### ISSUE TITLE
Self production Export not working

### ISSUE THREAD

**Issue by xtreamjava** [OpenEVSE/openevse_esp32_firmware#727]
I have mqtt topic providing +/- values in w. After new firmware update, it stopped working when I set mode to **Export**.
![Screenshot_20230923_130957](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/92907712/7668837e-ceb9-42d5-bde1-0a64dd92550e)

But when I switch mode to **Production** it starts displaying values
![Screenshot_20230923_131040](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/92907712/e92ba32b-7a4a-4fa9-a47e-5d0ee410da80)

Firmware: OpenEVSE Wifi v5.0.0

**Comment by xtreamjava** [comment]
Fixed after reset.

**Comment by danepowell** [comment]
Seeing this issue clued me into a related issue: the upgrade from v4.2.2 to v5.0.0 doesn't preserve the production vs export setting. Mine was previously set to export and somehow got switched to production after the upgrade. I wouldn't be surprised if this is related to you having the "jiggle the handle" (reset) to get it working.

**Comment by Zuikkis** [comment]
I have this very same issue and it's not fixing itself.. :(

I upgraded from 4.x to 5.1. In Export mode, I can't see negative watts at all, if mqtt sends -5000 watts in OpenEVSE is showing 0W. Positive watts do show.

**Comment by Zuikkis** [comment]
Ok, factory reset fixed it. But apparently the settings were ruined by firmware upgrade 4->5.
