### ISSUE TITLE
Update stoplight docs? 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/openevse_esp32_firmware#732]
How can we edit the stoplight docs? I've noticed a dead link on this page: https://openevse.stoplight.io/docs/openevse-wifi-v4/221999f7bb3e5-list-evse-claims

Here's the dead link, it looks like it's still using the old repo: https://openevse.stoplight.io/docs/openevse-wifi-v4/src/evse_man.h#L25

**Comment by jeremypoulter** [comment]
Those docs are generated from <https://github.com/OpenEVSE/openevse_esp32_firmware/blob/master/api.yml>
