### ISSUE TITLE
Let's Encrypt CA is out of date

### ISSUE THREAD

**Issue by basak** [OpenEVSE/openevse_esp32_firmware#806]
Hi,

MQTT has stopped working for me. OpenEVSE is unable to connect to my MQTT broker unless I accept self-signed certificates.

I noticed that the Let's Encrypt certificate on my broker has rotated and the certificate chain served is now shorter. This appears to be because of https://community.letsencrypt.org/t/shortening-the-lets-encrypt-chain-of-trust/201580. I believe the trusted LE CA on the firmware needs adjusting accordingly.

I found https://github.com/OpenEVSE/openevse_esp32_firmware/blob/master/src/root_ca.cpp but that doesn't look like it has changed recently.

I'm currently using:
 * 7.1.3.T2
 * 4.0.0

I'd be happy to update if I could figure out how! But AFAICT, this issue will affect the latest firmware also, unless there's some other source from the CA apart from the file above?

Thanks,

Robie

**Comment by jeremypoulter** [comment]
Thanks for letting us know. That is indeed the file to update with the new Root CA
