### ISSUE TITLE
5.10 RFID not working with new LCD wifi controller

### ISSUE THREAD

**Issue by rbray89** [OpenEVSE/openevse_esp32_firmware#807]
I've been attempting to get RFID working on the new LCD wifi unit.

I've connected a PN532 board via the SDA/SCL I2C header on the board, but can't get scans to show up. The PN532 powers up fine.

It seems the RFID config also is always available,  even if no hardware is attached.

**Comment by rbray89** [comment]
Created https://github.com/OpenEVSE/openevse_esp32_firmware/pull/819 to address this issue.

**Comment by Dicion** [comment]
If #819  fixed this, I think this can be closed? Can you confirm that it works now with the latest dev build?

**Comment by rbray89** [comment]
Looks like SDA and SCL might be swapped in the pinout.

**Comment by rbray89** [comment]
#865

**Comment by rbray89** [comment]
Looks like these changes fixed it!
