### ISSUE TITLE
Wrong consumption values on 3-phase connection

### ISSUE THREAD

**Issue by vermut** [OpenEVSE/openevse_esp32_firmware#809]
OpenEVSE reports consistent set of metrics, but they don't line up with other sensors outside OpenEVSE. It's like it's using max current for calculations instead of actual current.

### OpenEVSE world
![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/779376/a05bbf7b-f922-4f1b-9645-4643377b40d7)

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/779376/26d87e59-44fc-4113-be64-7d9b49e28168)

2.5h * 21A * 220V * 3 phases = ~34kWh

21A is the limit set in OpenEVSE. Everything is consistent with each other.

### Everything else
I'm charging RAV4 plugin that has battery size 18 kWh. Power sensors on solar inverter and data from electric company roughly match each other and say that during that period only  ~7kWh was consumed. They may be inaccurate but not THAT inaccurate.

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/779376/8170c17b-311d-4cc6-b4c8-d4b34be3ff6e)

And my **daily** consumption (those are accurate from electric company) is never even reaching this value.
![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/779376/e6868efe-65d5-4098-877c-17349ce3659d)

---

OpenEVSE: 	8.2.3.T2 	
OpenEVSE Wifi: 	v5.1.0_modified
![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/779376/cfbcb09f-1ae1-4aed-b22e-e69befdf8eea)

**Comment by zerodur12** [comment]
the RAV4 on board charger (AC) is a 6.6kW - 28A/230V **1 phase** Maximum charging power AC.

Even you have a 3 phase charger you will charge using only on 1 phase. 
in 3 phase OPENEVSE Charger the current is mesure only on 1 phase, it compute the power on 1 phase and multiply the result by 3 assuming the 2 other phase are loaded with the same current. 

1 your case 2 phases are unloaded the repported power is wrong and has to be divide by 3...

**Comment by vermut** [comment]
If it's one phase, maybe the solution would be switch OpenEVSE to 1-phase mode?

**Comment by vermut** [comment]
I did that.
