### ISSUE TITLE
OCPP - GetCompositeSchedule returns unknown variable?

### ISSUE THREAD

**Issue by retrocoder-78** [OpenEVSE/openevse_esp32_firmware#856]
Hello all!

Been testing the OCPP side and behaviour compared to other OCPP units. Today was charging at 16 amps set in the openevse firmware. Was unsure as to why (pretty sure it was to be set to 32 amps) so thought I would do a steVe GetCompositeSchedule to see how the station is currently set.

It returned the screenshot. Usually if the unit is set to let's say, 24 amps, the OCPP command will return 24 amps if requesting the information in amps.

@matth-x Any thoughts?

Thank you for your time! :)

![Screenshot from 2024-06-07 10-01-16](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/68619253/789d8642-b862-4976-9c66-22e76240b6e6)

**Comment by matth-x** [comment]
Hi @retrocoder-78,

Thanks for sharing this finding. The OCPP client actually only reports the load limits defined by OCPP Charging Profiles and the value -1 means that no limit is defined. MicroOcpp has no interface to also report the schedule from the local load balancer or other load management services (just hasn't been requested yet).

To monitor the maximum charge rate as advertised by the control pilot, you can add the measurand "Current.Offered" to the list of MeterValuesSampledData.

Do you have further findings where the OpenEVSE behaves different from other chargers?

**Comment by retrocoder-78** [comment]
Great information! The value of -1 and the explanation makes sense. I am testing some other popular OEM hardware at the moment. I'll report back shortly as to the return of the GetCompositeSchedule request and it's result.

Cheers! :smile:

**Comment by retrocoder-78** [comment]
Hello!

My apologies for the delay. The OEM charge box I am testing is fairly common in the market place. It's manufactured by LITEON Technology. They are rebranded by many companies.
![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/68619253/de6a2da8-52ef-4673-a13c-87600c2c6c08)

When no OCPP charge profile is loaded, the GetCompositeSchedule command returns the current Control Pilot setting. This box ships by default set at 40 amps. So, this is what the command returned.

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/68619253/013a7d79-0a31-4319-a2ba-45798ce7190f)

Taking a look in the firmware, there's an area to check what OCPP charge profiles might be loaded.

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/68619253/047c76e2-ab4a-44c3-b190-c92f53e527a7)

This is a nice feature, as once charge profiles are loaded via SteVe, keeping track of this and their stack can be problematic.

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/68619253/66d3fd8f-df8f-4733-9020-00a0e81985a6)

Okay, so that's the report back from inside this very common charge box. 

If there's anything further I can report back on, please don't hesitate to let me know. 😄

Cheers! 

> Hi @retrocoder-78,
> 
> Thanks for sharing this finding. The OCPP client actually only reports the load limits defined by OCPP Charging Profiles and the value -1 means that no limit is defined. MicroOcpp has no interface to also report the schedule from the local load balancer or other load management services (just hasn't been requested yet).
> 
> To monitor the maximum charge rate as advertised by the control pilot, you can add the measurand "Current.Offered" to the list of MeterValuesSampledData.
> 
> Do you have further findings where the OpenEVSE behaves different from other chargers?

**Comment by matth-x** [comment]
Thank you for the further details! I will consider reporting the default limit in the Composite Schedule, because it really makes sense to me.

**Comment by retrocoder-78** [comment]
Amazing! Glad this helped the cause. 

Cheers!

> Thank you for the further details! I will consider reporting the default limit in the Composite Schedule, because it really makes sense to me.
