### ISSUE TITLE
ocpp server connect fail

### ISSUE THREAD

**Issue by liyong4github** [OpenEVSE/openevse_esp32_firmware#873]
I am unable to connect to the OCPP server. Can anyone help me identify the problem? Here is the error message:

[MO] warning (MicroOcppMongooseClient.cpp:261): Insecure connection (WS)
[MO] info (RequestQueue.cpp:45): operation timeout: BootNotification
[MO] warning (MicroOcppMongooseClient.cpp:485): connection ws://xx.xx.xx.xx/steve/websocket/CentralSysremService/test01 -- HTTP error 404
[MO] info (MicroOcppMongooseClient.cpp:511): connection ws://xx.xx.xx.xx/steve/websocket/CentralSysremService/test01 -- closed
OpenEVSE not responding or not connected

**Comment by matth-x** [comment]
HTTP error 404 means that the charger can reach the server, but the server doesn't recognize the URL. The backend URL you posted contains a typo:

ws://xx.xx.xx.xx/steve/websocket/CentralSys**r**emService

**Comment by liyong4github** [comment]
@matth-x I'm so stupid. Thank you so much.
