### ISSUE TITLE
Schedule not working: inmediate start charging with any schedule 

### ISSUE THREAD

**Issue by jdgarcia99** [OpenEVSE/openevse_esp32_firmware#911]
Hi, 

I'm experiencing problems when trying to use the scheduler timer

Whatever schedule I create, it starts charging the car as soon as I create any schedule for the future

See Image attached

![IMG_2893](https://github.com/user-attachments/assets/dc064bf5-66d6-4767-9fc8-785a5a731564)

**Comment by jeremypoulter** [comment]
You need to create another schedule to stop the charge

**Comment by jdgarcia99** [comment]
OK, that makes sense. 

Thanks Jeremy
